### ISSUE TITLE
Install auto-updater

### ISSUE THREAD

**Issue by JoeTheHuman** [HexxiumCreations/Scammer-Bingo-Reborn#17]
Install an auto-updater. Will be updated after vacation.

**Comment by cake2** [comment]
I have an idea how this could work. 
Step 1: Download a txt file that contains the latest version number.
Step 2: If the latest version number is different from the current version, download the newest version.
Step 3: Install

**Comment by cake2** [comment]
I am not experienced with networking in VB, if it is simple i will help with this further. We just need to figure out how to automatically install, though.

**Comment by JoeTheHuman** [comment]
0cfe48591a47f687cf1e7b8899de3473ff953b64
