### ISSUE TITLE
IndexOutOfRange

### ISSUE THREAD

**Issue by JoeTheHuman** [HexxiumCreations/Scammer-Bingo-Reborn#22]
An IndexOutOfRange Exception is thrown when trying to add a button. Line 29 of [ButtonTextInput.cs](https://github.com/JoeTheHuman/Scammer-Bingo-Reborn/blob/master/Scammer%20Bingo%20Reborn/ButtonTextInput.cs)

**Comment by cake2** [comment]
Slightly fixed. Added a commit that adds a warning. **This does not fix the issue 100%.**

**Comment by XeliteXirish** [comment]
Not in ide or anything and barely looked but you sure its not just starting from 1 and no 0?

**Comment by JoeTheHuman** [comment]
I've located where it breaks, but I don't want to break anything else in the process of trying to fix it.
