### ISSUE TITLE
Error 404 not found when trying to download an updated version

### ISSUE THREAD

**Issue by imDema** [HexxiumCreations/Scammer-Bingo-Reborn#28]
in [UpdateBackend.cs](https://github.com/HexxiumCreations/Scammer-Bingo-Reborn/blob/master/Scammer%20Bingo%20Reborn/UpdateBackend.cs) line 48

**Comment by JoeTheHuman** [comment]
Working on it

**Comment by JoeTheHuman** [comment]
Fixed - 0cfe48591a47f687cf1e7b8899de3473ff953b64
